version: '3.8'

services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_DEBUG=true
      - FASTAPI_REDIS_URL=redis://redis:6379/0
      - FASTAPI_CELERY_BROKER_URL=redis://redis:6379/0
      - FASTAPI_CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FASTAPI_UPLOAD_DIR=/tmp/audio_merge
    depends_on:
      - redis
    volumes:
      - ./backend/tmp:/tmp/audio_merge
      - ./backend:/app
    networks:
      - audio-merge-network

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A api.celery_app:celery worker --loglevel=info --concurrency=2
    environment:
      - FASTAPI_REDIS_URL=redis://redis:6379/0
      - FASTAPI_CELERY_BROKER_URL=redis://redis:6379/0
      - FASTAPI_CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FASTAPI_UPLOAD_DIR=/tmp/audio_merge
    depends_on:
      - redis
    volumes:
      - ./backend/tmp:/tmp/audio_merge
      - ./backend:/app
    networks:
      - audio-merge-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - audio-merge-network

  flower:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A api.celery_app:celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - FASTAPI_REDIS_URL=redis://redis:6379/0
      - FASTAPI_CELERY_BROKER_URL=redis://redis:6379/0
      - FASTAPI_CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker
    networks:
      - audio-merge-network

volumes:
  redis-data:

networks:
  audio-merge-network:
    driver: bridge
